# Generated by Django 4.0.4 on 2022-04-25 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='notess',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/notes'),
            preserve_default=False,
        ),
    ]
