# Generated by Django 4.0.4 on 2022-04-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subject_notess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='notess',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=255)),
                ('notess', models.FileField(upload_to='static/notes')),
                ('subname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
