# Generated by Django 3.2.2 on 2022-04-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_subject_notess_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
